/* DO NOT EDIT, file generated by nestjs-i18n */

/* eslint-disable */
/* prettier-ignore */
import { Path } from "nestjs-i18n";
/* prettier-ignore */
export type I18nTranslations = {
    "enum": {
        "NSMember": {
            "EAddressType": {
                "HOME": string;
                "COMPANY": string;
            };
            "EMembershipType": {
                "PERSONAL": string;
                "ENTERPRISE": string;
            };
            "EMemberType": {
                "MEMBER": string;
                "COLLABORATOR": string;
                "POST_OFFICE": string;
            };
            "EStatus": {
                "INACTIVE": string;
                "ACTIVE": string;
                "WAITING_FOR_VERIFY": string;
                "DELETED": string;
                "WAITING_FOR_APPROVE": string;
            };
            "EBusinessType": {
                "LED_ADVERTISEMENT": string;
                "SOCIAL_SECURITY_CARD": string;
                "TOURISM": string;
                "HEALTH": string;
                "SME360": string;
            };
        };
    };
    "member": {
        "AuthMemberService": {
            "error": {
                "member_existed": string;
                "member_not_existed": string;
            };
        };
    };
    "payment": {
        "hello": string;
        "notification": {
            "upgrade_collaborator": {
                "title": string;
                "body": string;
            };
            "purchase_card": {
                "title": string;
                "body": string;
            };
        };
    };
    "validation": {
        "NOT_EMPTY": string;
        "INVALID_EMAIL": string;
        "INVALID_BOOLEAN": string;
        "MIN": string;
        "MAX": string;
    };
    "withdraw": {
        "WithdrawService": {
            "error": {
                "out_of_limit": string;
            };
        };
    };
};
/* prettier-ignore */
export type I18nPath = Path<I18nTranslations>;
